name=CastorS 
version=Beta test 1.0.0
author=rii66
maintainer=rii66
sentence=univ solder station core
paragraph=Original station module packaged as an Arduino library.
category=Device Control
architectures=c3 supermini android flash 
depends=Cerberus
